### ISSUE TITLE
Misaligned ptr

### ISSUE THREAD

**Issue by George-Miao** [pjtatlow/jammdb#26]
Error: 

```
thread 'db::test::test_db' panicked at 'misaligned pointer dereference: address must be a multiple of 0x8 but is 0x7f877000191c', src/index.crates.io-6f17d22bba15001f/jammdb-0.9.0/src/freelist.rs:64:29
```

Code:

```rust
use jammdb::DB;

#[test]
fn test_db() -> Result<(), Box<dyn std::error::Error>> {
    let db = DB::open("data/123.db")?;

    let tx = db.tx(true)?;
    tx.create_bucket("test")?;
    tx.commit()?;

    Ok(())
}
```

Version:

```
cargo 1.71.0-nightly (d0a4cbcee 2023-04-16)
rustc 1.71.0-nightly (fec9adcdb 2023-04-21)
jammdb: 0.9.0
system: Linux 6.2.8-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC x86_64 GNU/Linux
```

**Comment by pjtatlow** [comment]
Hmm, this is an interesting one. Only happens on nightly, not stable. Do you know of any changes to 1.71 that might impact pointer alignment?

**Comment by George-Miao** [comment]
> Hmm, this is an interesting one. Only happens on nightly, not stable. Do you know of any changes to 1.71 that might impact pointer alignment?

Yes. I believe they added panic on misaligned ptr dereference to 1.71 in debug builds. This is a bug for sure, expect that it did not cause any error until now.

**Comment by pjtatlow** [comment]
@George-Miao thanks for reporting this! Sorry the fix took so long. I'll cut a new release now.
