### ISSUE TITLE
can't open boltdb file

### ISSUE THREAD

**Issue by jackyzjk** [pjtatlow/jammdb#32]
I have a boltdb config file which generate in go language, I want to read it using jammdb, but it panic when I open it, the error as follows:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `4`,
 right: `3`', /home/jicky/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-be2141875385cea5/jammdb-0.10.0/src/page.rs:69:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)
```

**Comment by pjtatlow** [comment]
jammdb is not compatible with databases from BoltDB. It's heavily inspired by bolt, but not 100% file compatible.
