### ISSUE TITLE
[question] Is there way to list all the buckets 

### ISSUE THREAD

**Issue by ArunGust** [pjtatlow/jammdb#7]
Hi, 

Is there any way to list all the buckets in DB.

**Comment by pjtatlow** [comment]
Hmm, you can iterate over the items inside a bucket, so if you nest all of your buckets inside of another one, you could iterate over them that way. 

Technically I don't see any reason to not allow listing all of the top level buckets, I just haven't done it yet! Let me see if it's something I can add quickly though, I do see that being a useful thing to have!

**Comment by ArunGust** [comment]
thank you. I thought it might help to manage buckets. DB crashed for some reason, is there any log file ?

**Comment by pjtatlow** [comment]
No, and I'm not sure it makes sense to have one. Since only your program runs it, your program should have been the one to catch the "crash". What happened specifically?

**Comment by ArunGust** [comment]
ok, thanks, for now, I just rebuild the DB. I am still in the early stages

**Comment by pjtatlow** [comment]
Sounds good, if you can figure out any repro steps let me know!

Also, I've just released version `0.5.0` which should give you the (buckets)[https://docs.rs/jammdb/0.5.0/jammdb/struct.Transaction.html#method.buckets] method on a transaction or the (sub_buckets)[https://docs.rs/jammdb/0.5.0/jammdb/struct.Bucket.html#method.sub_buckets] method on any bucket
